# Generated by Django 4.0.8 on 2026-03-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_code_alter_course_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('学士', '学士学位'), ('硕士', '硕士学位')], max_length=25),
        ),
    ]
