#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
全面翻译脚本 - 处理所有常见的翻译模式
"""
import os
import re

# 扩展的翻译映射
TRANSLATIONS = {
    # 基础词汇
    "{% trans 'Learning management system' %}": "学习管理系统",
    "{% trans 'Home' %}": "首页",
    "{% trans 'Dashboard' %}": "仪表板",
    "{% trans 'Profile' %}": "个人资料",
    "{% trans 'Students' %}": "学生",
    "{% trans 'Lecturers' %}": "讲师",
    "{% trans 'Add' %}": "添加",
    "{% trans 'Update' %}": "更新",
    "{% trans 'Delete' %}": "删除",
    "{% trans 'Edit' %}": "编辑",
    "{% trans 'Save' %}": "保存",
    "{% trans 'Cancel' %}": "取消",
    "{% trans 'Action' %}": "操作",
    "{% trans 'Actions' %}": "操作",
    "{% trans 'Email' %}": "邮箱",
    "{% trans 'Password' %}": "密码",
    "{% trans 'Course' %}": "课程",
    "{% trans 'Courses' %}": "课程",
    "{% trans 'Program' %}": "项目",
    "{% trans 'Programs' %}": "项目",
    "{% trans 'Quiz' %}": "测验",
    "{% trans 'Quizzes' %}": "测验",
    "{% trans 'Result' %}": "结果",
    "{% trans 'Results' %}": "结果",
    "{% trans 'Semester' %}": "学期",
    "{% trans 'Session' %}": "学期",
    "{% trans 'My Courses' %}": "我的课程",
    "{% trans 'My courses' %}": "我的课程",
    "{% trans 'Admin Panel' %}": "管理面板",
    "{% trans 'Setting' %}": "设置",
    "{% trans 'Signout' %}": "退出",
    "{% trans 'Change Password' %}": "修改密码",
    "{% trans 'Account Setting' %}": "账户设置",
    "{% trans 'Personal Info' %}": "个人信息",
    "{% trans 'First Name:' %}": "名：",
    "{% trans 'Last Name:' %}": "姓：",
    "{% trans 'ID No.:' %}": "身份证号：",
    "{% trans 'ID No.' %}": "身份证号",
    "{% trans 'Full Name' %}": "全名",
    "{% trans 'Mob No.' %}": "手机号",
    "{% trans 'Address/city' %}": "地址/城市",
    "{% trans 'Address/city:' %}": "地址/城市：",
    "{% trans 'Last login' %}": "最后登录",
    "{% trans 'Last login:' %}": "最后登录：",
    "{% trans 'Role:' %}": "角色：",
    "{% trans 'Role' %}": "角色",
    "{% trans 'Edit Profile' %}": "编辑资料",
    "{% trans 'Change password' %}": "修改密码",
    "{% trans 'No courses assigned!' %}": "未分配课程！",
    "{% trans 'Applicant Info' %}": "申请人信息",
    "{% trans 'School:' %}": "学校：",
    "{% trans 'School' %}": "学校",
    "{% trans 'Level:' %}": "级别：",
    "{% trans 'Level' %}": "级别",
    "{% trans 'Contact Info' %}": "联系信息",
    "{% trans 'Email:' %}": "邮箱：",
    "{% trans 'Tel No.:' %}": "电话：",
    "{% trans 'Tel No.' %}": "电话",
    "{% trans 'Important Dates' %}": "重要日期",
    "{% trans 'Academic Year:' %}": "学年：",
    "{% trans 'Academic Year' %}": "学年",
    "{% trans 'Registered Date:' %}": "注册日期：",
    "{% trans 'Registered Date' %}": "注册日期",
    "{% trans 'Add Student' %}": "添加学生",
    "{% trans 'Add Lecturer' %}": "添加讲师",
    "{% trans 'Download pdf' %}": "下载PDF",
    "{% trans 'Download PDF' %}": "下载PDF",
    "{% trans 'No Student.' %}": "无学生。",
    "{% trans 'Add Student Now.' %}": "立即添加学生。",
    "{% trans 'No Lecturer(s).' %}": "无讲师。",
    "{% trans 'Add Lecturer Now.' %}": "立即添加讲师。",
    "{% trans 'Course Registration' %}": "课程注册",
    "{% trans 'Course Add' %}": "添加课程",
    "{% trans 'Drop' %}": "退选",
    "{% trans 'Drop Course' %}": "退选课程",
    "{% trans 'Calender is off' %}": "日历已关闭",
    "{% trans 'Check the university calender' %}": "请检查大学日历",
    "{% trans 'Save Score' %}": "保存分数",
    "{% trans 'Add Selected' %}": "添加所选",
    "{% trans 'First Semester:' %}": "第一学期：",
    "{% trans 'Second Semester:' %}": "第二学期：",
    "{% trans 'Mark' %}": "标记",
    "{% trans 'Course Code' %}": "课程代码",
    "{% trans 'Course Title' %}": "课程标题",
    "{% trans 'Course Name' %}": "课程名称",
    "{% trans 'Cr.Hr(s)' %}": "学分",
    "{% trans 'Cr.Hr' %}": "学分",
    "{% trans 'Year' %}": "年份",
    "{% trans 'Classification' %}": "分类",
    "{% trans 'Elective Group' %}": "选修组",
    "{% trans 'Elective' %}": "选修",
    "{% trans 'Core' %}": "核心",
    "{% trans 'No Course.' %}": "无课程。",
    "{% trans 'First semester Credit(s):' %}": "第一学期学分：",
    "{% trans 'Second semester credit(s):' %}": "第二学期学分：",
    "{% trans 'Registerd course credit(s):' %}": "已注册课程学分：",
    "{% trans 'Total credit(s):' %}": "总学分：",
    "{% trans 'Course Drop' %}": "退选课程",
    "{% trans 'Drop Selected' %}": "退选所选",
    "{% trans 'Print Registration Form' %}": "打印注册表单",
    "{% trans 'Print Registerd Courses' %}": "打印已注册课程",
    "{% trans 'Add Quiz' %}": "添加测验",
    "{% trans 'Questions' %}": "问题",
    "{% trans 'Question' %}": "问题",
    "{% trans 'Grade Results' %}": "成绩结果",
    "{% trans 'Grade' %}": "等级",
    "{% trans 'GRADE' %}": "等级",
    "{% trans 'Points' %}": "分数",
    "{% trans 'Point' %}": "分数",
    "{% trans 'Comment' %}": "评论",
    "{% trans 'PASS' %}": "通过",
    "{% trans 'FAIL' %}": "未通过",
    "{% trans 'Total first semester credit:' %}": "第一学期总学分：",
    "{% trans 'First Semester GPA:' %}": "第一学期GPA：",
    "{% trans 'Total second semester credit:' %}": "第二学期总学分：",
    "{% trans 'Total Credit:' %}": "总学分：",
    "{% trans 'Second Semester GPA:' %}": "第二学期GPA：",
    "{% trans 'Previous CGPA:' %}": "之前CGPA：",
    "{% trans 'Password Reset' %}": "密码重置",
    "{% trans 'Request Password Reset' %}": "请求密码重置",
    "{% trans 'Password Reset Complete' %}": "密码重置完成",
    "{% trans 'Your password has been set, you are now able to Log In!' %}": "您的密码已设置，现在可以登录！",
    "{% trans 'Sign In Here' %}": "在此登录",
    "{% trans 'Email sent' %}": "邮件已发送",
    "{% trans 'An Email has been sent with instructions\nto reset your password, check your email.' %}": "已发送包含密码重置说明的邮件，请检查您的邮箱。",
    "{% trans 'Back To Login' %}": "返回登录",
    "{% trans 'Confirm New Password' %}": "确认新密码",
    "{% trans 'Reset Password' %}": "重置密码",
    "{% trans 'Create Your Account' %}": "创建您的账户",
    "{% trans 'Login Form' %}": "登录表单",
    "{% trans 'Invalid ID & Password.' %}": "无效的身份证号和密码。",
    "{% trans 'SIGN UP' %}": "注册",
    "{% trans 'Already Registered ?' %}": "已注册？",
    "{% trans 'Login' %}": "登录",
    "{% trans 'Sign in' %}": "登录",
    "{% trans 'SIGN IN' %}": "登录",
    "{% trans 'ID Number' %}": "身份证号",
    "{% trans 'Forgot password ?' %}": "忘记密码？",
    "{% trans 'Add New Post' %}": "添加新文章",
    "{% trans 'News' %}": "新闻",
    "{% trans 'Events' %}": "事件",
    "{% trans 'news' %}": "新闻",
    "{% trans 'events' %}": "事件",
    "{% trans 'ago' %}": "前",
    "{% trans 'School news and events will appear here.' %}": "学校新闻和事件将显示在这里。",
    "{% trans 'Post form' %}": "文章表单",
    "{% trans 'Post Form' %}": "文章表单",
    "{% trans 'Semester list' %}": "学期列表",
    "{% trans 'Add New Semester' %}": "添加新学期",
    "{% trans 'Semester List' %}": "学期列表",
    "{% trans 'Is Current semester' %}": "当前学期",
    "{% trans 'Next Semester Begins' %}": "下学期开始",
    "{% trans 'No Semester.' %}": "无学期。",
    "{% trans 'Add Semester Now.' %}": "立即添加学期。",
    "{% trans 'Semester Form' %}": "学期表单",
    "{% trans 'Semester Add & update Form' %}": "学期添加和更新表单",
    "{% trans 'Session List' %}": "学期列表",
    "{% trans 'Add New Session' %}": "添加新学期",
    "{% trans 'Is Current Session' %}": "当前学期",
    "{% trans 'Next Session Begins' %}": "下学期开始",
    "{% trans 'No Session.' %}": "无学期。",
    "{% trans 'Add Session Now.' %}": "立即添加学期。",
    "{% trans 'Session Form' %}": "学期表单",
    "{% trans 'Session Add & update Form' %}": "学期添加和更新表单",
    "{% trans 'Programs & Courses' %}": "项目和课程",
    "{% trans 'Course Form' %}": "课程表单",
    "{% trans 'Course Detail' %}": "课程详情",
    "{% trans 'Other Info' %}": "其他信息",
    "{% trans 'Course Allocations' %}": "课程分配",
    "{% trans 'Allocation Form' %}": "分配表单",
    "{% trans 'Course Allocation Form' %}": "课程分配表单",
    "{% trans 'Allocation list' %}": "分配列表",
    "{% trans 'Allocate Now' %}": "立即分配",
    "{% trans 'Edit or Update' %}": "编辑或更新",
    "{% trans 'Deallocate' %}": "取消分配",
    "{% trans 'No Course Allocated.' %}": "未分配课程。",
    "{% trans 'Allocate now' %}": "立即分配",
    "{% trans 'My courses' %}": "我的课程",
    "{% trans 'Edit course' %}": "编辑课程",
    "{% trans 'Upload new file' %}": "上传新文件",
    "{% trans 'Upload new video' %}": "上传新视频",
    "{% trans 'Take a Quiz' %}": "参加测验",
    "{% trans 'Video Tutorials' %}": "视频教程",
    "{% trans 'Video Title' %}": "视频标题",
    "{% trans 'Uploaded Date' %}": "上传日期",
    "{% trans 'Get Started' %}": "开始",
    "{% trans 'Play now' %}": "立即播放",
    "{% trans 'No video Uploaded.' %}": "未上传视频。",
    "{% trans 'Upload now.' %}": "立即上传。",
    "{% trans 'Documentations' %}": "文档",
    "{% trans 'File name' %}": "文件名",
    "{% trans 'Updated Date' %}": "更新日期",
    "{% trans 'Downloads' %}": "下载",
    "{% trans 'Download' %}": "下载",
    "{% trans 'No File Uploaded.' %}": "未上传文件。",
    "{% trans 'Lecturer(s)' %}": "讲师",
    "{% trans 'No lecturer assigned for this course' %}": "未为此课程分配讲师",
    "{% trans 'Program Form' %}": "项目表单",
    "{% trans 'Program Add Form' %}": "项目添加表单",
    "{% trans 'Add Program' %}": "添加项目",
    "{% trans 'Program List' %}": "项目列表",
    "{% trans 'Program Name' %}": "项目名称",
    "{% trans 'Summary' %}": "摘要",
    "{% trans 'No program.' %}": "无项目。",
    "{% trans 'Add program now.' %}": "立即添加项目。",
    "{% trans 'Add Course' %}": "添加课程",
    "{% trans 'Current Semester' %}": "当前学期",
    "{% trans 'No course for this progrm.' %}": "此项目无课程。",
    "{% trans 'Add one now.' %}": "立即添加。",
    "{% trans 'Taken Courses:' %}": "已选课程：",
    "{% trans 'Taken' %}": "已选",
    "{% trans 'All Courses:' %}": "所有课程：",
    "{% trans 'Invoices' %}": "发票",
    "{% trans 'Pay now' %}": "立即支付",
    "{% trans 'Search All... #course, #program, #Quiz, #News, #Events' %}": "搜索全部... #课程, #项目, #测验, #新闻, #事件",
    "{% trans 'Privacy' %}": "隐私",
    "{% trans 'and' %}": "和",
    "{% trans 'Terms of use.' %}": "使用条款。",
    "{% trans 'Read our' %}": "阅读我们的",
    "{% trans '⭐️ Star This Project' %}": "⭐️ 为项目加星",
    "{% trans 'File upload' %}": "文件上传",
    "{% trans 'File upload for' %}": "文件上传（用于",
    "{% trans 'File Upload Form' %}": "文件上传表单",
    "{% trans 'Upload' %}": "上传",
    "{% trans 'Video upload' %}": "视频上传",
    "{% trans 'Video upload for' %}": "视频上传（用于",
    "{% trans 'Video Upload Form' %}": "视频上传表单",
    "{% trans 'No video description set.' %}": "未设置视频描述。",
    "{% trans 'Others' %}": "其他",
    "{% trans 'Lecturer Add Form' %}": "讲师添加表单",
    "{% trans 'Student Add Form' %}": "学生添加表单",
    "{% trans 'Lecturer Update Form' %}": "讲师更新表单",
    "{% trans 'Student Update Form' %}": "学生更新表单",
    "{% trans 'Change Program' %}": "更改项目",
    "{% trans 'First Name' %}": "名",
    "{% trans 'Last Name' %}": "姓",
    "{% trans 'Hawas Preparatory School' %}": "Hawas预备学校",
    "{% trans 'Bad request' %}": "错误请求",
    "{% trans 'Please make sure the form is correctly filled.' %}": "请确保表单填写正确。",
    "{% trans 'Return to the app' %}": "返回应用",
    "{% trans 'forbidden' %}": "禁止",
    "{% trans 'You need the proper permission to make that request.' %}": "您需要适当的权限才能发出该请求。",
    "{% trans 'Looks like the page you' %}": "看起来您要查找的页面",
    "{% trans 'Server error' %}": "服务器错误",
    "{% trans 'Please try again later.' %}": "请稍后再试。",
    "{% trans 'Manage Score' %}": "管理分数",
    "{% trans 'Select Your Course Here' %}": "在此选择您的课程",
    "{% trans 'No course.' %}": "无课程。",
    "{% trans 'To manage scores, please select the course using the button above.' %}": "要管理分数，请使用上面的按钮选择课程。",
    "{% trans 'Students result form' %}": "学生成绩表单",
    "{% trans 'Grade report' %}": "成绩报告",
    "{% trans 'Mid exam' %}": "期中考试",
    "{% trans 'Attendance' %}": "出勤",
    "{% trans 'Final exam' %}": "期末考试",
    "{% trans 'Total' %}": "总计",
    "{% trans 'Assesment Results' %}": "评估结果",
    "{% trans 'Manage' %}": "管理",
    "{% trans 'students' %}": "学生",
    "{% trans 'sessions' %}": "学期",
    "{% trans 'semesters' %}": "学期",
    "{% trans 'Switch' %}": "切换",
    "{% trans 'programs' %}": "项目",
    "{% trans 'course allocations' %}": "课程分配",
    "{% trans 'Password Change' %}": "密码修改",
    "{% trans 'Account setting' %}": "账户设置",
    "{% trans 'Account Settings' %}": "账户设置",
    "{% trans 'Update Profile' %}": "更新资料",
    "{% trans 'Search result for' %}": "搜索结果（",
    "{% trans 'Search' %}": "搜索",
    "{% trans 'result' %}": "结果",
    "{% trans 'Program of' %}": "项目（",
    "{% trans 'News And Events' %}": "新闻和事件",
    "{% trans 'Date:' %}": "日期：",
    "{% trans 'quiz' %}": "测验",
    "{% trans 'Course:' %}": "课程：",
    "{% trans 'Search by:' %}": "搜索方式：",
    "{% trans 'Title or Description' %}": "标题或描述",
    "{% trans 'Title, Code or Description' %}": "标题、代码或描述",
    "{% trans 'Title, Description or just by typing news or event' %}": "标题、描述或直接输入新闻或事件",
    "{% trans 'Title, Description or Category(practice, assignment and exam)' %}": "标题、描述或类别（练习、作业和考试）",
    "{% trans 'Complete Exams' %}": "已完成考试",
    "{% trans 'Quiz Progress Rec' %}": "测验进度记录",
    "{% trans 'Course Allocation' %}": "课程分配",
    "{% trans 'Manage Session' %}": "管理学期",
    "{% trans 'Manage Semester' %}": "管理学期",
    "{% trans 'Dashboard settings' %}": "仪表板设置",
    "{% trans 'Display grid' %}": "显示网格",
    "{% trans 'Display table' %}": "显示表格",
    "{% trans 'Manage dashboard' %}": "管理仪表板",
    "{% trans 'Administrators' %}": "管理员",
    "{% trans 'Lab Assistance' %}": "实验室助理",
    "{% trans 'Librarians' %}": "图书管理员",
    "{% trans 'Supervisors' %}": "督导",
    "{% trans 'Office Assistance' %}": "办公室助理",
    "{% trans 'Latest activities' %}": "最新活动",
    "{% trans 'No recent activity' %}": "无最近活动",
    "{% trans 'School Demographics' %}": "学校人口统计",
}

def translate_file(file_path):
    """翻译单个文件"""
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        original_content = content
        
        # 应用所有翻译
        for en, zh in TRANSLATIONS.items():
            content = content.replace(en, zh)
        
        # 如果内容有变化，保存文件
        if content != original_content:
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"已处理: {file_path}")
            return True
        return False
    except Exception as e:
        print(f"处理 {file_path} 时出错: {e}")
        return False

def main():
    """主函数"""
    templates_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'templates')
    
    # 获取所有HTML文件
    html_files = []
    for root, dirs, files in os.walk(templates_dir):
        for file in files:
            if file.endswith('.html'):
                html_files.append(os.path.join(root, file))
    
    print(f"找到 {len(html_files)} 个HTML文件")
    
    translated_count = 0
    for file_path in html_files:
        if translate_file(file_path):
            translated_count += 1
    
    print(f"\n处理完成！共处理 {translated_count} 个文件")

if __name__ == '__main__':
    main()
